// START WITH CLASS AcceptToRoom
//   Extends Message
//       Field: direction
//       Field: room_name
//       Field: room_owner
// START WITH CLASS Persona
//   Extends Friend
//       Field: remark
//       Field: room
//       Field: dhmut
//   Extends Member
//       Field: name
//       Field: hash
//       Field: alias
//       Field: dhpub
//       Field: hub
//       Field: contact
// START WITH CLASS Friend
//   Extends Member
//       Field: name
//       Field: hash
//       Field: alias
//       Field: dhpub
//       Field: hub
//       Field: contact
// START WITH CLASS Member
// START WITH CLASS MembersOfRoom
//   Extends Message
//       Field: direction
//       Field: room_name
//       Field: room_owner
// START WITH CLASS Message
// START WITH CLASS DhRequest
// START WITH CLASS Room
// START WITH CLASS AutoMessage
//   Extends TextMessage
//       Field: text
//   Extends Message
//       Field: direction
//       Field: room_name
//       Field: room_owner
// START WITH CLASS TextMessage
//   Extends Message
//       Field: direction
//       Field: room_name
//       Field: room_owner
// START WITH CLASS InviteToRoom
//   Extends Message
//       Field: direction
//       Field: room_name
//       Field: room_owner
// DO NOT EDIT THIS FILE.  It is generated from protocol.txt by compile-proto.tcl.

package yak.server;

import java.util.ArrayList;
import yak.etc.Bytes;
import yak.etc.Yak;

public abstract class Proto extends Yak {

  public abstract int classId();
  public abstract Bytes pickle();

  public static final int IdAcceptToRoom = 58;
  public static final int IdAutoMessage = 61;
  public static final int IdDhRequest = 53;
  public static final int IdFriend = 51;
  public static final int IdInviteToRoom = 57;
  public static final int IdMember = 50;
  public static final int IdMembersOfRoom = 56;
  public static final int IdMessage = 54;
  public static final int IdPersona = 52;
  public static final int IdRoom = 49;
  public static final int IdTextMessage = 55;

  public static class AcceptToRoom extends Message {  // = 58
    public int classId() { return 58; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        sb.append(" direction: " + 
          direction
        );
        sb.append(" room_name: " + 
          (room_name == null ? "null" :CurlyEncode(room_name))
        );
        sb.append(" room_owner: " + 
          (room_owner == null ? "null" :CurlyEncode(room_owner))
        );
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 58
    Bytes b = new Bytes();
    b.appendProtoInt (0, 58);  // Class Id 58
    b.appendProtoInt (1, this.direction);
    if (this.room_name != null) b.appendProtoString (2, this.room_name);
    if (this.room_owner != null) b.appendProtoString (3, this.room_owner);
    return b;
  }

  }

  public static class AutoMessage extends TextMessage {  // = 61
    int kind;  // = 5
    public int classId() { return 61; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        sb.append(" direction: " + 
          direction
        );
        sb.append(" kind: " + 
          kind
        );
        sb.append(" room_name: " + 
          (room_name == null ? "null" :CurlyEncode(room_name))
        );
        sb.append(" room_owner: " + 
          (room_owner == null ? "null" :CurlyEncode(room_owner))
        );
        sb.append(" text: " + 
          (text == null ? "null" :CurlyEncode(text))
        );
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 61
    Bytes b = new Bytes();
    b.appendProtoInt (0, 61);  // Class Id 61
    b.appendProtoInt (1, this.direction);
    if (this.room_name != null) b.appendProtoString (2, this.room_name);
    if (this.room_owner != null) b.appendProtoString (3, this.room_owner);
    if (this.text != null) b.appendProtoString (4, this.text);
    b.appendProtoInt (5, this.kind);
    return b;
  }

  }

  public static class DhRequest extends Proto {  // = 53
    String dhpub;  // = 2
    String name;  // = 1
    public int classId() { return 53; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        sb.append(" dhpub: " + 
          (dhpub == null ? "null" :CurlyEncode(dhpub))
        );
        sb.append(" name: " + 
          (name == null ? "null" :CurlyEncode(name))
        );
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 53
    Bytes b = new Bytes();
    b.appendProtoInt (0, 53);  // Class Id 53
    if (this.name != null) b.appendProtoString (1, this.name);
    if (this.dhpub != null) b.appendProtoString (2, this.dhpub);
    return b;
  }

  }

  public static class Friend extends Member {  // = 51
    String dhmut;  // = 9
    String remark;  // = 7
    ArrayList<Room> room = new ArrayList<Room>();  // = 8
    public int classId() { return 51; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        sb.append(" alias: " + 
          (alias == null ? "null" :CurlyEncode(alias))
        );
        sb.append(" contact: " + 
          (contact == null ? "null" :CurlyEncode(contact))
        );
        sb.append(" dhmut: " + 
          (dhmut == null ? "null" :CurlyEncode(dhmut))
        );
        sb.append(" dhpub: " + 
          (dhpub == null ? "null" :CurlyEncode(dhpub))
        );
        sb.append(" hash: " + 
          (hash == null ? "null" :CurlyEncode(hash))
        );
        for (int i = 0; i < hub.size(); ++i) {
          String x = hub.get(i);
        sb.append(" hub: " + 
          (x == null ? "null" :CurlyEncode(x))
        );
        }
        sb.append(" name: " + 
          (name == null ? "null" :CurlyEncode(name))
        );
        sb.append(" remark: " + 
          (remark == null ? "null" :CurlyEncode(remark))
        );
        for (int i = 0; i < room.size(); ++i) {
          Room x = room.get(i);
        sb.append(" room: " + 
          (x == null ? "null" : room.toString())
        );
        }
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 51
    Bytes b = new Bytes();
    b.appendProtoInt (0, 51);  // Class Id 51
    if (this.name != null) b.appendProtoString (1, this.name);
    if (this.hash != null) b.appendProtoString (2, this.hash);
    if (this.alias != null) b.appendProtoString (3, this.alias);
    if (this.dhpub != null) b.appendProtoString (4, this.dhpub);
      for (int i = 0; i < this.hub.size(); i++) {
        b.appendProtoString (5, this.hub.get(i));
      } // next i
    if (this.contact != null) b.appendProtoString (6, this.contact);
    if (this.remark != null) b.appendProtoString (7, this.remark);
      for (int i = 0; i < this.room.size(); i++) {
        if (this.room.get(i) != null) {
	      b.appendProtoBytes (8, this.room.get(i).pickle());
        }
      } // next i
    if (this.dhmut != null) b.appendProtoString (9, this.dhmut);
    return b;
  }

  }

  public static class InviteToRoom extends Message {  // = 57
    ArrayList<String> member_names = new ArrayList<String>();  // = 4
    public int classId() { return 57; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        sb.append(" direction: " + 
          direction
        );
        for (int i = 0; i < member_names.size(); ++i) {
          String x = member_names.get(i);
        sb.append(" member_names: " + 
          (x == null ? "null" :CurlyEncode(x))
        );
        }
        sb.append(" room_name: " + 
          (room_name == null ? "null" :CurlyEncode(room_name))
        );
        sb.append(" room_owner: " + 
          (room_owner == null ? "null" :CurlyEncode(room_owner))
        );
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 57
    Bytes b = new Bytes();
    b.appendProtoInt (0, 57);  // Class Id 57
    b.appendProtoInt (1, this.direction);
    if (this.room_name != null) b.appendProtoString (2, this.room_name);
    if (this.room_owner != null) b.appendProtoString (3, this.room_owner);
      for (int i = 0; i < this.member_names.size(); i++) {
        b.appendProtoString (4, this.member_names.get(i));
      } // next i
    return b;
  }

  }

  public static class Member extends Proto {  // = 50
    String alias;  // = 3
    String contact;  // = 6
    String dhpub;  // = 4
    String hash;  // = 2
    ArrayList<String> hub = new ArrayList<String>();  // = 5
    String name;  // = 1
    public int classId() { return 50; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        sb.append(" alias: " + 
          (alias == null ? "null" :CurlyEncode(alias))
        );
        sb.append(" contact: " + 
          (contact == null ? "null" :CurlyEncode(contact))
        );
        sb.append(" dhpub: " + 
          (dhpub == null ? "null" :CurlyEncode(dhpub))
        );
        sb.append(" hash: " + 
          (hash == null ? "null" :CurlyEncode(hash))
        );
        for (int i = 0; i < hub.size(); ++i) {
          String x = hub.get(i);
        sb.append(" hub: " + 
          (x == null ? "null" :CurlyEncode(x))
        );
        }
        sb.append(" name: " + 
          (name == null ? "null" :CurlyEncode(name))
        );
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 50
    Bytes b = new Bytes();
    b.appendProtoInt (0, 50);  // Class Id 50
    if (this.name != null) b.appendProtoString (1, this.name);
    if (this.hash != null) b.appendProtoString (2, this.hash);
    if (this.alias != null) b.appendProtoString (3, this.alias);
    if (this.dhpub != null) b.appendProtoString (4, this.dhpub);
      for (int i = 0; i < this.hub.size(); i++) {
        b.appendProtoString (5, this.hub.get(i));
      } // next i
    if (this.contact != null) b.appendProtoString (6, this.contact);
    return b;
  }

  }

  public static class MembersOfRoom extends Message {  // = 56
    ArrayList<Member> members = new ArrayList<Member>();  // = 4
    public int classId() { return 56; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        sb.append(" direction: " + 
          direction
        );
        for (int i = 0; i < members.size(); ++i) {
          Member x = members.get(i);
        sb.append(" members: " + 
          (x == null ? "null" : members.toString())
        );
        }
        sb.append(" room_name: " + 
          (room_name == null ? "null" :CurlyEncode(room_name))
        );
        sb.append(" room_owner: " + 
          (room_owner == null ? "null" :CurlyEncode(room_owner))
        );
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 56
    Bytes b = new Bytes();
    b.appendProtoInt (0, 56);  // Class Id 56
    b.appendProtoInt (1, this.direction);
    if (this.room_name != null) b.appendProtoString (2, this.room_name);
    if (this.room_owner != null) b.appendProtoString (3, this.room_owner);
      for (int i = 0; i < this.members.size(); i++) {
        if (this.members.get(i) != null) {
	      b.appendProtoBytes (4, this.members.get(i).pickle());
        }
      } // next i
    return b;
  }

  }

  public static class Message extends Proto {  // = 54
    int direction;  // = 1
    String room_name;  // = 2
    String room_owner;  // = 3
    public int classId() { return 54; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        sb.append(" direction: " + 
          direction
        );
        sb.append(" room_name: " + 
          (room_name == null ? "null" :CurlyEncode(room_name))
        );
        sb.append(" room_owner: " + 
          (room_owner == null ? "null" :CurlyEncode(room_owner))
        );
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 54
    Bytes b = new Bytes();
    b.appendProtoInt (0, 54);  // Class Id 54
    b.appendProtoInt (1, this.direction);
    if (this.room_name != null) b.appendProtoString (2, this.room_name);
    if (this.room_owner != null) b.appendProtoString (3, this.room_owner);
    return b;
  }

  }

  public static class Persona extends Friend {  // = 52
    String dhsec;  // = 11
    ArrayList<Friend> friend = new ArrayList<Friend>();  // = 12
    public int classId() { return 52; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        sb.append(" alias: " + 
          (alias == null ? "null" :CurlyEncode(alias))
        );
        sb.append(" contact: " + 
          (contact == null ? "null" :CurlyEncode(contact))
        );
        sb.append(" dhmut: " + 
          (dhmut == null ? "null" :CurlyEncode(dhmut))
        );
        sb.append(" dhpub: " + 
          (dhpub == null ? "null" :CurlyEncode(dhpub))
        );
        sb.append(" dhsec: " + 
          (dhsec == null ? "null" :CurlyEncode(dhsec))
        );
        for (int i = 0; i < friend.size(); ++i) {
          Friend x = friend.get(i);
        sb.append(" friend: " + 
          (x == null ? "null" : friend.toString())
        );
        }
        sb.append(" hash: " + 
          (hash == null ? "null" :CurlyEncode(hash))
        );
        for (int i = 0; i < hub.size(); ++i) {
          String x = hub.get(i);
        sb.append(" hub: " + 
          (x == null ? "null" :CurlyEncode(x))
        );
        }
        sb.append(" name: " + 
          (name == null ? "null" :CurlyEncode(name))
        );
        sb.append(" remark: " + 
          (remark == null ? "null" :CurlyEncode(remark))
        );
        for (int i = 0; i < room.size(); ++i) {
          Room x = room.get(i);
        sb.append(" room: " + 
          (x == null ? "null" : room.toString())
        );
        }
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 52
    Bytes b = new Bytes();
    b.appendProtoInt (0, 52);  // Class Id 52
    if (this.name != null) b.appendProtoString (1, this.name);
    if (this.hash != null) b.appendProtoString (2, this.hash);
    if (this.alias != null) b.appendProtoString (3, this.alias);
    if (this.dhpub != null) b.appendProtoString (4, this.dhpub);
      for (int i = 0; i < this.hub.size(); i++) {
        b.appendProtoString (5, this.hub.get(i));
      } // next i
    if (this.contact != null) b.appendProtoString (6, this.contact);
    if (this.remark != null) b.appendProtoString (7, this.remark);
      for (int i = 0; i < this.room.size(); i++) {
        if (this.room.get(i) != null) {
	      b.appendProtoBytes (8, this.room.get(i).pickle());
        }
      } // next i
    if (this.dhmut != null) b.appendProtoString (9, this.dhmut);
    if (this.dhsec != null) b.appendProtoString (11, this.dhsec);
      for (int i = 0; i < this.friend.size(); i++) {
        if (this.friend.get(i) != null) {
	      b.appendProtoBytes (12, this.friend.get(i).pickle());
        }
      } // next i
    return b;
  }

  }

  public static class Room extends Proto {  // = 49
    ArrayList<String> member = new ArrayList<String>();  // = 4
    String name;  // = 1
    String owner;  // = 2
    String title;  // = 3
    public int classId() { return 49; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        for (int i = 0; i < member.size(); ++i) {
          String x = member.get(i);
        sb.append(" member: " + 
          (x == null ? "null" :CurlyEncode(x))
        );
        }
        sb.append(" name: " + 
          (name == null ? "null" :CurlyEncode(name))
        );
        sb.append(" owner: " + 
          (owner == null ? "null" :CurlyEncode(owner))
        );
        sb.append(" title: " + 
          (title == null ? "null" :CurlyEncode(title))
        );
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 49
    Bytes b = new Bytes();
    b.appendProtoInt (0, 49);  // Class Id 49
    if (this.name != null) b.appendProtoString (1, this.name);
    if (this.owner != null) b.appendProtoString (2, this.owner);
    if (this.title != null) b.appendProtoString (3, this.title);
      for (int i = 0; i < this.member.size(); i++) {
        b.appendProtoString (4, this.member.get(i));
      } // next i
    return b;
  }

  }

  public static class TextMessage extends Message {  // = 55
    String text;  // = 4
    public int classId() { return 55; }
    public String toString() {
      StringBuilder sb = new StringBuilder("{");
        sb.append(" direction: " + 
          direction
        );
        sb.append(" room_name: " + 
          (room_name == null ? "null" :CurlyEncode(room_name))
        );
        sb.append(" room_owner: " + 
          (room_owner == null ? "null" :CurlyEncode(room_owner))
        );
        sb.append(" text: " + 
          (text == null ? "null" :CurlyEncode(text))
        );
      sb.append("}");
      return sb.toString();
    }
  public Bytes pickle () {  // = 55
    Bytes b = new Bytes();
    b.appendProtoInt (0, 55);  // Class Id 55
    b.appendProtoInt (1, this.direction);
    if (this.room_name != null) b.appendProtoString (2, this.room_name);
    if (this.room_owner != null) b.appendProtoString (3, this.room_owner);
    if (this.text != null) b.appendProtoString (4, this.text);
    return b;
  }

  }

public static AcceptToRoom UnpickleAcceptToRoom (Bytes b) {  // = 58
  System.err.printf("UnpickleAcceptToRoom: %s\n", b.showProto());
  AcceptToRoom z = new AcceptToRoom ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (1 << 3) | 0: { z.direction = b.popVarInt(); }
        break;
      case (2 << 3) | 2: { z.room_name = b.popVarString(); }
        break;
      case (3 << 3) | 2: { z.room_owner = b.popVarString(); }
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 58) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in AcceptToRoom: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle AcceptToRoom


public static AutoMessage UnpickleAutoMessage (Bytes b) {  // = 61
  System.err.printf("UnpickleAutoMessage: %s\n", b.showProto());
  AutoMessage z = new AutoMessage ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (1 << 3) | 0: { z.direction = b.popVarInt(); }
        break;
      case (5 << 3) | 0: { z.kind = b.popVarInt(); }
        break;
      case (2 << 3) | 2: { z.room_name = b.popVarString(); }
        break;
      case (3 << 3) | 2: { z.room_owner = b.popVarString(); }
        break;
      case (4 << 3) | 2: { z.text = b.popVarString(); }
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 61) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in AutoMessage: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle AutoMessage


public static DhRequest UnpickleDhRequest (Bytes b) {  // = 53
  System.err.printf("UnpickleDhRequest: %s\n", b.showProto());
  DhRequest z = new DhRequest ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (2 << 3) | 2: { z.dhpub = b.popVarString(); }
        break;
      case (1 << 3) | 2: { z.name = b.popVarString(); }
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 53) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in DhRequest: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle DhRequest


public static Friend UnpickleFriend (Bytes b) {  // = 51
  System.err.printf("UnpickleFriend: %s\n", b.showProto());
  Friend z = new Friend ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (3 << 3) | 2: { z.alias = b.popVarString(); }
        break;
      case (6 << 3) | 2: { z.contact = b.popVarString(); }
        break;
      case (9 << 3) | 2: { z.dhmut = b.popVarString(); }
        break;
      case (4 << 3) | 2: { z.dhpub = b.popVarString(); }
        break;
      case (2 << 3) | 2: { z.hash = b.popVarString(); }
        break;
      case (5 << 3) | 2: { z.hub.add(b.popVarString()); }
        break;
      case (1 << 3) | 2: { z.name = b.popVarString(); }
        break;
      case (7 << 3) | 2: { z.remark = b.popVarString(); }
        break;
      case (8 << 3) | 2: {
         Bytes b2 = b.popVarBytes();
         Room p2 = UnpickleRoom (b2);
         z.room.add(p2);
      } // end case
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 51) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in Friend: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle Friend


public static InviteToRoom UnpickleInviteToRoom (Bytes b) {  // = 57
  System.err.printf("UnpickleInviteToRoom: %s\n", b.showProto());
  InviteToRoom z = new InviteToRoom ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (1 << 3) | 0: { z.direction = b.popVarInt(); }
        break;
      case (4 << 3) | 2: { z.member_names.add(b.popVarString()); }
        break;
      case (2 << 3) | 2: { z.room_name = b.popVarString(); }
        break;
      case (3 << 3) | 2: { z.room_owner = b.popVarString(); }
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 57) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in InviteToRoom: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle InviteToRoom


public static Member UnpickleMember (Bytes b) {  // = 50
  System.err.printf("UnpickleMember: %s\n", b.showProto());
  Member z = new Member ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (3 << 3) | 2: { z.alias = b.popVarString(); }
        break;
      case (6 << 3) | 2: { z.contact = b.popVarString(); }
        break;
      case (4 << 3) | 2: { z.dhpub = b.popVarString(); }
        break;
      case (2 << 3) | 2: { z.hash = b.popVarString(); }
        break;
      case (5 << 3) | 2: { z.hub.add(b.popVarString()); }
        break;
      case (1 << 3) | 2: { z.name = b.popVarString(); }
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 50) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in Member: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle Member


public static MembersOfRoom UnpickleMembersOfRoom (Bytes b) {  // = 56
  System.err.printf("UnpickleMembersOfRoom: %s\n", b.showProto());
  MembersOfRoom z = new MembersOfRoom ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (1 << 3) | 0: { z.direction = b.popVarInt(); }
        break;
      case (4 << 3) | 2: {
         Bytes b2 = b.popVarBytes();
         Member p2 = UnpickleMember (b2);
         z.members.add(p2);
      } // end case
        break;
      case (2 << 3) | 2: { z.room_name = b.popVarString(); }
        break;
      case (3 << 3) | 2: { z.room_owner = b.popVarString(); }
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 56) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in MembersOfRoom: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle MembersOfRoom


public static Message UnpickleMessage (Bytes b) {  // = 54
  System.err.printf("UnpickleMessage: %s\n", b.showProto());
  Message z = new Message ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (1 << 3) | 0: { z.direction = b.popVarInt(); }
        break;
      case (2 << 3) | 2: { z.room_name = b.popVarString(); }
        break;
      case (3 << 3) | 2: { z.room_owner = b.popVarString(); }
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 54) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in Message: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle Message


public static Persona UnpicklePersona (Bytes b) {  // = 52
  System.err.printf("UnpicklePersona: %s\n", b.showProto());
  Persona z = new Persona ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (3 << 3) | 2: { z.alias = b.popVarString(); }
        break;
      case (6 << 3) | 2: { z.contact = b.popVarString(); }
        break;
      case (9 << 3) | 2: { z.dhmut = b.popVarString(); }
        break;
      case (4 << 3) | 2: { z.dhpub = b.popVarString(); }
        break;
      case (11 << 3) | 2: { z.dhsec = b.popVarString(); }
        break;
      case (12 << 3) | 2: {
         Bytes b2 = b.popVarBytes();
         Friend p2 = UnpickleFriend (b2);
         z.friend.add(p2);
      } // end case
        break;
      case (2 << 3) | 2: { z.hash = b.popVarString(); }
        break;
      case (5 << 3) | 2: { z.hub.add(b.popVarString()); }
        break;
      case (1 << 3) | 2: { z.name = b.popVarString(); }
        break;
      case (7 << 3) | 2: { z.remark = b.popVarString(); }
        break;
      case (8 << 3) | 2: {
         Bytes b2 = b.popVarBytes();
         Room p2 = UnpickleRoom (b2);
         z.room.add(p2);
      } // end case
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 52) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in Persona: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle Persona


public static Room UnpickleRoom (Bytes b) {  // = 49
  System.err.printf("UnpickleRoom: %s\n", b.showProto());
  Room z = new Room ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (4 << 3) | 2: { z.member.add(b.popVarString()); }
        break;
      case (1 << 3) | 2: { z.name = b.popVarString(); }
        break;
      case (2 << 3) | 2: { z.owner = b.popVarString(); }
        break;
      case (3 << 3) | 2: { z.title = b.popVarString(); }
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 49) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in Room: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle Room


public static TextMessage UnpickleTextMessage (Bytes b) {  // = 55
  System.err.printf("UnpickleTextMessage: %s\n", b.showProto());
  TextMessage z = new TextMessage ();
  while (b.len > 0) {
    int code = b.popVarInt();
    System.err.println(Fmt("Code %d:%d", code >> 3, code & 7));
    switch (code) {
      case (1 << 3) | 0: { z.direction = b.popVarInt(); }
        break;
      case (2 << 3) | 2: { z.room_name = b.popVarString(); }
        break;
      case (3 << 3) | 2: { z.room_owner = b.popVarString(); }
        break;
      case (4 << 3) | 2: { z.text = b.popVarString(); }
        break;
      case 0:  {int clsid = b.popVarInt(); if (clsid != 55) { throw new RuntimeException("Bad clsid: " + clsid); }}
        break;
      default:
        // Some day, ignore extra fields.  For now, call it an error.
        throw new RuntimeException("Bad tag code in TextMessage: " + code); 
    }  // end switch
  }  // end while
  return z;
}  // end Unpickle TextMessage


  public static Proto Unpickle(Bytes b) {
    if (b.arr[b.off] == 0) {
      int clsid = b.arr[b.off + 1];  // HACK works for clsid < 128
      switch (clsid) {
        case 58 : return UnpickleAcceptToRoom (b);
        case 61 : return UnpickleAutoMessage (b);
        case 53 : return UnpickleDhRequest (b);
        case 51 : return UnpickleFriend (b);
        case 57 : return UnpickleInviteToRoom (b);
        case 50 : return UnpickleMember (b);
        case 56 : return UnpickleMembersOfRoom (b);
        case 54 : return UnpickleMessage (b);
        case 52 : return UnpicklePersona (b);
        case 49 : return UnpickleRoom (b);
        case 55 : return UnpickleTextMessage (b);
      }
      throw new RuntimeException("Bad cls id in Proto.Unpickle: " + clsid); 
    }
    throw new RuntimeException("Missing cls id in Proto.Unpickle");
  }

}
